version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    links:
      - shortening
      - redirection
  
  shortening: 
    build: 
      context: ./shortening
      dockerfile: Dockerfile-shortening
    links:
      - db
    # ports: 
    #   - "5000:5000"
    
    env_file:
     - ./config.env


  redirection: 
    build: 
      context: ./redirection
      dockerfile: Dockerfile-redirection
    links:
      - db
    # ports:
    #   - "50001:5000"
    env_file:
     - ./config.env

  db:
    image: mysql:5.7
    # ports:
    #   - "3306:3306"
    
    env_file:
     - ./config.env
    
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql